import type { Product, Review } from "@/types";

export const products: Product[] = [
  {
    id: "forest-tee",
    slug: "forest-tee",
    name: "Forest Oversized Tee",
    category: "Minimal",
    collection: "Signature",
    price: 48,
    rating: 4.9,
    badge: "Best Seller",
    description:
      "A premium oversized tee with sculpted shoulders, premium cotton, and a relaxed silhouette built for every day.",
    details: [
      "240 GSM cotton blend",
      "Dropped shoulder silhouette",
      "Soft pigment dye finish",
      "Lightweight stretch for movement",
    ],
    colors: [
      { name: "Forest", value: "#1F3A2D" },
      { name: "Sand", value: "#D8C3A5" },
      { name: "Charcoal", value: "#1C1C1C" },
    ],
    sizes: ["S", "M", "L", "XL", "XXL"],
    tags: ["Minimal", "Adventure", "Best Seller"],
    images: [
      "/images/tshirt-1.svg",
      "/images/tshirt-2.svg",
    ],
  },
  {
    id: "sand-escape-tee",
    slug: "sand-escape-tee",
    name: "Sand Escape Tee",
    category: "Adventure",
    collection: "Launch",
    price: 52,
    rating: 4.8,
    badge: "New",
    description:
      "A fresh statement tee with a soft handfeel and a clean fit that layers easily with a jacket or hoodie.",
    details: [
      "Brushed cotton face",
      "Oversized drop arm",
      "Precision collar detail",
      "Sustainable dyes",
    ],
    colors: [
      { name: "Sand", value: "#D8C3A5" },
      { name: "Charcoal", value: "#1C1C1C" },
      { name: "Off White", value: "#F9F8F6" },
    ],
    sizes: ["S", "M", "L", "XL", "XXL"],
    tags: ["Adventure", "New"],
    images: [
      "/images/tshirt-2.svg",
      "/images/tshirt-3.svg",
    ],
  },
  {
    id: "charcoal-statement-tee",
    slug: "charcoal-statement-tee",
    name: "Charcoal Statement Tee",
    category: "Quotes",
    collection: "Signature",
    price: 54,
    rating: 4.7,
    badge: "Customizable",
    description:
      "A statement piece with bold piping detail and a generous fit designed to stand out while staying understated.",
    details: [
      "Heavyweight 240 GSM jersey",
      "Letterpress inspired graphics",
      "Relaxed body with extended length",
      "Fade-resistant color",
    ],
    colors: [
      { name: "Charcoal", value: "#1C1C1C" },
      { name: "Forest", value: "#1F3A2D" },
      { name: "Sand", value: "#D8C3A5" },
    ],
    sizes: ["S", "M", "L", "XL", "XXL"],
    tags: ["Quotes", "Customizable"],
    images: [
      "/images/tshirt-3.svg",
      "/images/tshirt-4.svg",
    ],
  },
  {
    id: "off-white-tee",
    slug: "off-white-tee",
    name: "Off White Oversized Tee",
    category: "Minimal",
    collection: "Essentials",
    price: 46,
    rating: 4.8,
    badge: "Best Seller",
    description: "A clean, infrared look with premium staple fabric and an oversized fit designed for layering.",
    details: ["Ultra-soft cotton", "Relaxed drop shoulder", "Minimal branding", "Breathable weave"],
    colors: [
      { name: "Off White", value: "#F9F8F6" },
      { name: "Charcoal", value: "#1C1C1C" },
      { name: "Sand", value: "#D8C3A5" },
    ],
    sizes: ["S", "M", "L", "XL", "XXL"],
    tags: ["Minimal", "Best Seller"],
    images: [
      "/images/tshirt-4.svg",
      "/images/tshirt-1.svg",
    ],
  },
  {
    id: "olive-field-tee",
    slug: "olive-field-tee",
    name: "Olive Field Tee",
    category: "Adventure",
    collection: "Outdoors",
    price: 50,
    rating: 4.7,
    badge: "New",
    description: "Rugged yet refined, this oversized tee is built for off-duty journeys and easy everyday wear.",
    details: ["Soft garment wash", "Structured collar", "Extended length", "Colorfast finish"],
    colors: [
      { name: "Olive", value: "#556B54" },
      { name: "Forest", value: "#1F3A2D" },
      { name: "Sand", value: "#D8C3A5" },
    ],
    sizes: ["S", "M", "L", "XL", "XXL"],
    tags: ["Adventure", "New"],
    images: [
      "/images/tshirt-1.svg",
      "/images/tshirt-2.svg",
    ],
  },
  {
    id: "charcoal-graphic-tee",
    slug: "charcoal-graphic-tee",
    name: "Charcoal Graphic Tee",
    category: "Quotes",
    collection: "Studio",
    price: 55,
    rating: 4.8,
    badge: "Customizable",
    description: "A statement tee with elevated graphic detail, designed to feel premium in a casual look.",
    details: ["Sculpted fit", "High-density print", "Heavyweight cotton", "Soft interior finish"],
    colors: [
      { name: "Charcoal", value: "#1C1C1C" },
      { name: "Black", value: "#000000" },
      { name: "White", value: "#F9F8F6" },
    ],
    sizes: ["S", "M", "L", "XL", "XXL"],
    tags: ["Quotes", "Customizable"],
    images: [
      "/images/tshirt-2.svg",
      "/images/tshirt-3.svg",
    ],
  },
  {
    id: "sand-geometry-tee",
    slug: "sand-geometry-tee",
    name: "Sand Geometry Tee",
    category: "Minimal",
    collection: "Signature",
    price: 53,
    rating: 4.9,
    badge: "Best Seller",
    description: "A refined neutral tee with tonal geometry and an oversized fit that feels understated and premium.",
    details: ["Cotton blend", "Dropped shoulder", "Subtle texture", "Shape-retaining weave"],
    colors: [
      { name: "Sand", value: "#D8C3A5" },
      { name: "White", value: "#F9F8F6" },
      { name: "Charcoal", value: "#1C1C1C" },
    ],
    sizes: ["S", "M", "L", "XL", "XXL"],
    tags: ["Minimal", "Best Seller"],
    images: [
      "/images/tshirt-3.svg",
      "/images/tshirt-4.svg",
    ],
  },
  {
    id: "short-run-tee",
    slug: "short-run-tee",
    name: "Short Run Tee",
    category: "Adventure",
    collection: "Limited",
    price: 58,
    rating: 4.8,
    badge: "New",
    description: "A limited release tee with premium details, brushed finishes, and a relaxed silhouette.",
    details: ["Limited run", "Heavy washed look", "Exclusive colorways", "Premium stitching"],
    colors: [
      { name: "Navy", value: "#2C3E50" },
      { name: "Charcoal", value: "#1C1C1C" },
      { name: "Sand", value: "#D8C3A5" },
    ],
    sizes: ["S", "M", "L", "XL", "XXL"],
    tags: ["Adventure", "New"],
    images: [
      "/images/tshirt-4.svg",
      "/images/tshirt-1.svg",
    ],
  },
  {
    id: "sunset-quote-tee",
    slug: "sunset-quote-tee",
    name: "Sunset Quote Tee",
    category: "Quotes",
    collection: "Studio",
    price: 56,
    rating: 4.7,
    badge: "Customizable",
    description: "A premium graphic tee designed around a bold phrase and a lifestyle-led oversized silhouette.",
    details: ["Soft print", "Relaxed fit", "Premium cotton", "Clean finish"],
    colors: [
      { name: "Sand", value: "#D8C3A5" },
      { name: "Charcoal", value: "#1C1C1C" },
      { name: "Off White", value: "#F9F8F6" },
    ],
    sizes: ["S", "M", "L", "XL", "XXL"],
    tags: ["Quotes", "Customizable", "New"],
    images: [
      "/images/tshirt-1.svg",
      "/images/tshirt-2.svg",
    ],
  },
  {
    id: "urban-echo-tee",
    slug: "urban-echo-tee",
    name: "Urban Echo Tee",
    category: "Minimal",
    collection: "Essentials",
    price: 49,
    rating: 4.8,
    badge: "Best Seller",
    description: "A balanced staple with tonal embroidery and a premium oversized body for easy daily wear.",
    details: ["Clean silhouette", "Soft handfeel", "Timeless style", "Structured shoulders"],
    colors: [
      { name: "Charcoal", value: "#1C1C1C" },
      { name: "Forest", value: "#1F3A2D" },
      { name: "Sand", value: "#D8C3A5" },
    ],
    sizes: ["S", "M", "L", "XL", "XXL"],
    tags: ["Minimal", "Best Seller"],
    images: [
      "/images/tshirt-2.svg",
      "/images/tshirt-3.svg",
    ],
  },
];

export const reviews: Review[] = [
  {
    id: "review-1",
    author: "Maya J.",
    rating: 5,
    title: "A perfect fit every time",
    message:
      "The fabric feels premium and the oversized fit is just right. This tee is the new everyday favorite.",
    date: "June 18, 2026",
  },
  {
    id: "review-2",
    author: "Noah R.",
    rating: 5,
    title: "Thoughtful details and quality",
    message:
      "I love the subtle design and the way it pairs with every look. Mojo Miles nailed the comfort.",
    date: "July 2, 2026",
  },
  {
    id: "review-3",
    author: "Anika S.",
    rating: 4.8,
    title: "Premium feel without the fuss",
    message:
      "The tee holds its shape after washing and feels luxurious on the skin. Exactly what I wanted.",
    date: "July 17, 2026",
  },
];
